Automatik(1)

# NAME 

Automatik - Gestionnaire de commandes amusantes pour linux.

# GENERAL PRINCIPLES
	Automatik est très simple d'utilisation.
	Le guide est directement dans l'appli.
	Pour lancer Automatik, tapez "automatik" dans le termainal après l'avoir compilé.

# AUTHORS
Maintained by Oscar B. <oscar us b att disroot dt org>. Sources can be found at
https://codeberg.org/Alcedinidae/Automatik.
